### ISSUE TITLE
fp.opener.open() not working as context manager with ZipFS

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#103]
The following code does not work with ZipFS:

```
import fs.opener

with fs.opener.open('zip://test.zip', writeable=False) as zf:
    zf.listdir('.')

```

```

Traceback (most recent call last):
  File "bin/zopepy", line 302, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "test.py", line 3, in <module>
    with fs.opener.open('zip://test.zip', writeable=False) as zf:
AttributeError: __exit__

```

**Comment by willmcgugan** [comment]
The `opener.open` method returns a tuple of `(<filesystem>, <path>)`

I'm guessing you want the `open_fs` method which returns just a filesystem. 

There's a shortcut for importing `open_fs`. Does this work?

```python
import fs
with fs.open_fs('zip://test.zip', writeable=False) as zf:
    zf.listdir('.')
```

**Comment by zopyx** [comment]
Yes, you are right. My mistake.
