### ISSUE TITLE
Weird UnboundLocalError with fs 2.0.15

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#104]
I have this weird UnboundLocalError with`fs.opener.open`:

```
-> result = fs.opener.open('zip://{}'.format(fn), writeable=False)
(Pdb) c
2017-11-10 14:56:17 ERROR Zope.SiteErrorLog 1510322177.580.315878516717 http://dev.zopyx.de:12020/Plone/test-document/current-publish
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module zopyx.plone.smashdocs.browser.versioneddocument, line 209, in current_publish
UnboundLocalError: local variable 'fs' referenced before assignment
```

However `fs` is available in exactly the same place:

```
(Pdb) print fs
<module 'fs' from '/home/ajung/.buildout/eggs/fs-2.0.15-py2.7.egg/fs/__init__.pyc'>
(Pdb) print fs.opener
<module 'fs.opener' from '/home/ajung/.buildout/eggs/fs-2.0.15-py2.7.egg/fs/opener/__init__.pyc'>
(Pdb) print fs.opener.open
<bound method Registry.open of <fs-registry ['ftp', 'osfs', 'usercache', 'temp', 'tar', 'userdata', 'mem', 'sitedata', 'file', 'userconf', 'userlog', 'zip', 'siteconf']>>

```

based on these imports:

```
import fs.path
import fs.opener
```

**Comment by zopyx** [comment]
My workaround is to use

```
import fs.opener as fs_opener
```
and then

```
result = fs_opener.open(...)
```

**Comment by willmcgugan** [comment]
That error is probably because you are importing `fs` but also assigning to a local variable called `fs`. It's a little surprising behaviour, but Python will assume you want the local variable even before you assign it in a function.

Here's an example which shows the same error:

```python
import fs
def broken():
    print(fs)
    fs = 5
broken()
```
```python
Traceback (most recent call last):
  File "fst.py", line 5, in <module>
    broken()
  File "fst.py", line 3, in broken
    print(fs)
UnboundLocalError: local variable 'fs' referenced before assignment
```

**Comment by willmcgugan** [comment]
Hi @zopyx Was that the issue? Tidying up issues...
