### ISSUE TITLE
(nonsense) symbolic link and isdir

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#132]
While playing around I found a problem with a wrong used link file. 

Example:

none existing file or directory of name foo but created as link.
```
mkdir TEST
cd TEST
ln -s foo foo
```

Python Example:
```
u = "~/TEST"
_fs = fs.open_fs(u)
_fs.isdir("foo")
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    _fs.isdir("foo")
  File "/user/miniconda3/envs/mssdev/lib/python3.6/site-packages/fs/base.py", line 744, in isdir
    return self.getinfo(path).is_dir
  File "/user/miniconda3/envs/mssdev/lib/python3.6/site-packages/fs/osfs.py", line 235, in getinfo
    _stat = os.lstat(sys_path)
  File "/user/miniconda3/envs/mssdev/lib/python3.6/site-packages/fs/error_tools.py", line 82, in __exit__
    traceback
  File "/user/miniconda3/envs/mssdev/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/user/miniconda3/envs/mssdev/lib/python3.6/site-packages/fs/osfs.py", line 233, in getinfo
    _stat = os.stat(sys_path)
fs.errors.OperationFailed: operation failed, [Errno 40] Zu viele Ebenen aus symbolischen Links: '/user/TEST/foo'

```

**Comment by willmcgugan** [comment]
I actually think this may be correct behaviour. The only improvement I could think of is to have a dedicate Exception for that, but I'm not sure that's worth the effort since the error message is clear and you can access `errno` on the `OperationFailed` exception.

Going to close this, but feel free to comment here if you think I should change my mind.
