### ISSUE TITLE
ZipFS fails to open nested file with non-ASCII name

### ISSUE THREAD

**Issue by fresheed** [PyFilesystem/pyfilesystem2#135]
ZipFS seems to fail when reading archived file with non-ASCII name:

```
# -*- encoding: UTF-8
from __future__ import unicode_literals
from fs.zipfs import ZipFS

with ZipFS("test_archive.zip", write=True) as zip_fs:
    zip_fs.settext("Файл", "some content")

with ZipFS("test_archive.zip") as zip_fs:
    fs_pathes=list(zip_fs.walk.files())
    print("FS filenames:", fs_pathes)
    print("Zipfile filenames:", zip_fs._zip.namelist())
    for path in fs_pathes:
        with zip_fs.openbin(path) as handle:
            print("Opened %s" % path)
```

Resulting output (Python2.7, Linux machine, master Pyfilesystem branch):
```
(u'FS filenames:', [u'/\u0424\u0430\u0439\u043b'])
(u'Zipfile filenames:', ['\xd0\xa4\xd0\xb0\xd0\xb9\xd0\xbb'])
Traceback (most recent call last):
  File "analyze_archive.py", line 16, in <module>
    with zip_fs.openbin(path) as handle:
  File "/home/fresheed/work/fix_registration/pyfilesystem2-master/fs/zipfs.py", line 371, in openbin
    return _ZipExtFile(self, zip_name)
  File "/home/fresheed/work/fix_registration/pyfilesystem2-master/fs/zipfs.py", line 33, in __init__
    self._end = _zip.getinfo(name).file_size
  File "/usr/lib64/python2.7/zipfile.py", line 905, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'\\u0424\\u0430\\u0439\\u043b' in the archive"
```

As we can see, zipfile accepts filenames as bytestrings, while Pyfilesystem operates with Unicode. 
Probable solution is:
```
class _ZipExtFile(RawWrapper):

    def __init__(self, fs, name):
        self._zip = _zip = fs._zip
        name=name.encode(fs.encoding) #convert filename using parent fs's encoding
        self._end = _zip.getinfo(name).file_size
        self._pos = 0
        super(_ZipExtFile, self).__init__(_zip.open(name), 'r', name)
```
but I don't sure if it is the only place to change.

**Comment by willmcgugan** [comment]
Fix in master. Would you mind giving it a try?

**Comment by fresheed** [comment]
Works fine now. Thank you for fast response!
