### ISSUE TITLE
  raise ValueError('path must not be bytes')

### ISSUE THREAD

**Issue by aliabbasjp** [PyFilesystem/pyfilesystem2#15]
I am getting following error ,although the same code works in other system:

```
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from fs.osfs import OSFS
>>> list_fs=OSFS(root_path=r'~/work/corpus/lists')
>>> hyphs=list_fs.open(r'cleaned.txt',encoding='utf8').readlines()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aliabbas/anaconda2/lib/python2.7/site-packages/fs/osfs.py", line 317, in open
    self.validatepath(path)
  File "/home/aliabbas/anaconda2/lib/python2.7/site-packages/fs/base.py", line 1108, in validatepath
    raise ValueError('path must not be bytes')

 list_fs.listdir(".")
[u'Spec', u'cleaned.txt']

```

**Comment by willmcgugan** [comment]
In PyFilesystem2 all paths must be unicode, so the error here is valid. Changing `r'cleaned.txt` to `u'cleaned.txt'` should fix it.
