### ISSUE TITLE
Unable to rename aka movedir a directory

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#241]
PyFilesystem 2.1.2: how can you rename a directory (local FS)?

```

(Pdb) handle.listdir('.')
['x']
(Pdb) handle.isdir('x')
True
(Pdb) handle.movedir('x', 'y')
*** fs.errors.ResourceNotFound: resource 'y' not found
```

**Comment by willmcgugan** [comment]
That could done with the `fs.move` module.

```python
fs.move(handle, 'x', handle, 'y')
```

Although you might have identified a weakness in the base interface. `movedir` doesn't have quite the same semantics as `move`.

**Comment by zopyx** [comment]
`movedir` seems to have issues with non-ascii names (Python 3.7 here):


```
>>> fs.move.move_dir(local, 'abc', local, 'def')
>>> fs.move.move_dir(local, 'def', local, 'üöä')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ajung/src/xmldirector.connector/lib/python3.7/site-packages/fs/move.py", line 88, in move_dir
    _dst_fs.makedir(dst_path, recreate=True)
  File "/home/ajung/src/xmldirector.connector/lib/python3.7/site-packages/fs/osfs.py", line 323, in makedir
    return self.opendir(_path)
  File "/home/ajung/src/xmldirector.connector/lib/python3.7/site-packages/fs/base.py", line 1167, in opendir
    raise errors.DirectoryExpected(path=path)
fs.errors.DirectoryExpected: path '/üöä' should be a directory

```

**Comment by willmcgugan** [comment]
What platform are you on? That works for me, on MacOS. Do't suppose /üöä exists and is a file?

**Comment by zopyx** [comment]
Ignore my last remark.

**Comment by willmcgugan** [comment]
@zopyx I completely forgot that [movedir](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.movedir) has a 'create' parameter that is required if the destination directory doesn't exit.

```python
handle.movedir('x', 'y', create=True)
```
