### ISSUE TITLE
TypeError when importing fs.zipfs from compiled library

### ISSUE THREAD

**Issue by hkethi002** [PyFilesystem/pyfilesystem2#267]
In the `_new_name` function in [base.py](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/base.py#L80), a doc string is assumed to be a string for every method, however for python that has been optimized by removing doc strings, `_method.__doc__` is a `NoneType`

Traceback:
```
>>> import fs.zipfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fs/zipfs.pyc", line 14, in <module>
  File "fs/base.pyc", line 92, in <module>
  File "fs/base.pyc", line 598, in FS
  File "fs/base.pyc", line 85, in _new_name
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by willmcgugan** [comment]
Fixed in v2.4.2
