### ISSUE TITLE
AttributeError: 'OSFS' object has no attribute 'strip' when using fs.compress.write_tar

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [PyFilesystem/pyfilesystem2#272]
Testing this code:

import fs.compress as compress
import fs.osfs as osfs
fs = osfs.OSFS('<local_dir>')
compress.write_tar(src_fs=fs,file='<tar_file>', compression='tar', walker=fs.walk)

Returns the error:

AttributeError: 'OSFS' object has no attribute 'strip' when using fs.compress.write_tar

Am i using write_tar correctly or is there a bug in this function?

**Comment by althonos** [comment]
Could you add the full traceback so that we can see which line raised the error ? Thanks.

**Comment by LuisMoralesAlonso** [comment]
Traceback (most recent call last):
  File "/home/luis/.PyCharmCE2018.3/config/scratches/scratch.py", line 7, in <module>
    compress.write_zip(src_fs=fs,file='/data/minio/persist/test.zip', compression=8, walker=fs.walk)
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/compress.py", line 61, in write_zip
    for path, info in gen_walk:
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 405, in info
    for _path, info in _walk:
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 429, in _walk_breadth
    depth = _calculate_depth(path)
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 134, in _calculate_depth
    _path = path.strip("/")
AttributeError: 'OSFS' object has no attribute 'strip'

**Comment by LuisMoralesAlonso** [comment]
It happens with zip too as you can see in the previous logs, but find here the logs with write_tar:

Traceback (most recent call last):
  File "/home/luis/.PyCharmCE2018.3/config/scratches/scratch.py", line 7, in <module>
    compress.write_tar(src_fs=fs,file='/data/minio/persist/test.tar', compression='tar', walker=fs.walk)
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/compress.py", line 153, in write_tar
    for path, info in gen_walk:
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 405, in info
    for _path, info in _walk:
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 429, in _walk_breadth
    depth = _calculate_depth(path)
  File "/home/luis/PycharmProjects/boaconnectors/venv/lib/python3.6/site-packages/fs/walk.py", line 134, in _calculate_depth
    _path = path.strip("/")
AttributeError: 'OSFS' object has no attribute 'strip'

Process finished with exit code 1

**Comment by willmcgugan** [comment]
The walker argument expects a `fs.walk.Walker` instance, but you are passing in `fs.walk` which is a `BoundWalker`. You can omit that argument, because the compress methods will do the right thing by default. A custom walker is only required if you have a customized Walker object.

The `compression` parameter should be one of `gz`, `bz2` or `xz` for the case of tar archives. That doesn't appear to be documented in the pyfilesystem docs, it probably should be.

Try replacing the following in your original code:

```python
compress.write_tar(src_fs, "foo.tar", compression="gz")
```

The compress module is perhaps a little low level. I tend to use the higher level copy methods to create archives

```python
from fs.copy import copy_fs
# Copy local directory "foo" to an archive called "foo.tar"
copy_fs("foo", "tar://foo.tar")
```

**Comment by LuisMoralesAlonso** [comment]
Thanks!!!! Now works...
