### ISSUE TITLE
Possible bug with MountFS setbinfile() and setbytes()

### ISSUE THREAD

**Issue by fresheed** [PyFilesystem/pyfilesystem2#33]
I try to run following code:
```
(pyfs) [fresheed@localhost pyfs_issue]$ ls -R
.:
temp1  temp2
./temp1:
temp.txt
./temp2:
```
```
(pyfs) [fresheed@localhost pyfs_issue]$ python2.7
...
>>> from fs.osfs import OSFS
>>> f1=OSFS("temp1")
>>> f2=OSFS("temp2")
>>> from fs.mountfs import MountFS
>>> root=MountFS()
>>> root.mount("f1", f1)
>>> root.mount("f2", f2)
>>> root.copy(u"f1/temp.txt", u"f2/temp.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/base.py", line 302, in copy
    self.setbinfile(dst_path, read_file)
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/mountfs.py", line 228, in setbinfile
    return fs.setbinfile(path, file)
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/base.py", line 977, in setbinfile
    with self.open(path, 'wb') as dst_file:
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/osfs.py", line 338, in open
    **options
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/error_tools.py", line 77, in __exit__
    traceback
  File "/home/fresheed/.virtualenvs/pyfs/lib/python2.7/site-packages/fs/osfs.py", line 338, in open
    **options
fs.errors.ResourceNotFound: resource 'f2/temp.txt' not found

```

Then I looked in mountfs.py and saw:
```
   def setbinfile(self, path, file):
        self.check()
        fs, _path = self._delegate(path)
        return fs.setbinfile(path, file)
```
So underlying FS receives full path, not delegated _path. Is it a bug or I misunderstood something?
If it's a bug, I can fix it and send you a pull request

**Comment by fresheed** [comment]
Just subclassed MountFS with overrode setbinfile() and setbytes() and got expected behaviour, so it really seems like a bug

**Comment by willmcgugan** [comment]
Yeah, that's a bug. Just pushed a fix to master. Would you mind giving it a try?

**Comment by fresheed** [comment]
Works well now. Thanks!
