### ISSUE TITLE
Windows makedirs does not accept full path

### ISSUE THREAD

**Issue by prescod** [PyFilesystem/pyfilesystem2#416]
This works okay on Unix-ish operating systems:

```
f = fs.open_fs("/tmp").makedirs("/tmp/xyzzy")
```

But this does not work on Windows:

```
>>> fs.open_fs("c:/Temp").makedirs("c:/Temp/bar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38\lib\site-packages\fs\base.py", line 1068, in makedirs
    dir_paths = tools.get_intermediate_dirs(self, path)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38\lib\site-packages\fs\tools.py", line 79, in get_intermediate_dirs
    resource = fs.getinfo(path)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38\lib\site-packages\fs\osfs.py", line 286, in getinfo
    _path = self.validatepath(path)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38\lib\site-packages\fs\osfs.py", line 678, in validatepath
    return super(OSFS, self).validatepath(path)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python38\lib\site-packages\fs\base.py", line 1489, in validatepath
    raise errors.InvalidCharsInPath(path)
fs.errors.InvalidCharsInPath: path '/c:/Temp/bar' contains invalid characters
```

**Comment by willmcgugan** [comment]
`makedirs` accepts an [FS path](https://docs.pyfilesystem.org/en/latest/concepts.html#paths). FS paths are relative to the FS object root and platform agnostic.

In your first example, you have created `/tmp/tmp/xyzzy`

In your second example, you probably want `fs.open_fs("c:/Temp").makedirs("/bar")`

**Comment by prescod** [comment]
Okay thank you. I probably read that 9 months ago but forgot about it.

**Comment by lurch** [comment]
There's also [TempFS](https://docs.pyfilesystem.org/en/latest/reference/tempfs.html) which means you don't need to worry about `/tmp` or `c:/Temp` :wink:
