### ISSUE TITLE
`OSFS.islink` raises an error on dangling symbolic links

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#427]
On Linux, `OSFS.islink` raises an error when given a path to a dangling symbolic link, where it should actually return `True`.

## Reproducing

```bash
$ ln -s some/non/existing/path link
$ python
```
```python
>>> import fs
>>> fs.open_fs(".").islink("link")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/althonos/.local/lib/python3.8/site-packages/fs/osfs.py", line 612, in islink
    raise errors.ResourceNotFound(path)
fs.errors.ResourceNotFound: resource 'link' not found
>>> folder.getinfo("link")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/althonos/.local/lib/python3.8/site-packages/fs/osfs.py", line 612, in islink
    raise errors.ResourceNotFound(path)
fs.errors.ResourceNotFound: resource 'link' not found
```

To summarize, here are the current behaviour with symlinks:
| Symlink type | OSFS.exists | OSFS.isdir | OSFS.isfile | OSFS.islink | OSFS.getinfo |
|---|---|---|---|---|---|
| dangling | `False` | `False` | `False` | **errors**  | **errors**  |
| existing file | `True` | `False` | `True` | `True` | :heavy_check_mark:  |
| existing directory | `True` | `True` | `False` | `True` | :heavy_check_mark:  |

Here is a comparison with the standard library in Python 3.8:
| Symlink type | os.path.exists | os.path.isdir | os.path.isfile | os.path.islink | os.path.lstat | os.path.stat |
|---|---|---|---|---|---|---|
| dangling | `False` | `False` | `False` | `True` | :heavy_check_mark: | **errors**  |
| existing file | `True` | `False` | `True` | `True` | :heavy_check_mark: | :heavy_check_mark:  |
| existing directory | `True` | `True` | `False` | `True` | :heavy_check_mark: | :heavy_check_mark:  |

I'd expect the correct behaviour here to be: `getinfo` actually returns without issue, `exists` is `False`, and `islink` is `True`. (We can debate wether `fs.exists(path)` should be `True` on a dangling symlink though)

**Comment by althonos** [comment]
Oops, duplicate of #411.
