### ISSUE TITLE
Remove usage of deprecated module pkg_resources

### ISSUE THREAD

**Issue by matrss** [PyFilesystem/pyfilesystem2#577]
Pyfilesystem2 makes use of this module which got deprecated at some point. This leads to noisy DeprecationWarning's in the test suite of a project using pyfilesystem2.

To reproduce:
```
>>> import warnings
>>> warnings.resetwarnings()
>>> import fs
/home/icg149/mambaforge/envs/fs-report/lib/python3.11/site-packages/fs/__init__.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
/home/icg149/mambaforge/envs/fs-report/lib/python3.11/site-packages/fs/__init__.py:4: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('fs')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
/home/icg149/mambaforge/envs/fs-report/lib/python3.11/site-packages/fs/opener/__init__.py:6: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('fs.opener')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
/home/icg149/mambaforge/envs/fs-report/lib/python3.11/site-packages/pkg_resources/__init__.py:2350: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('fs')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(parent)
```

**Comment by matrss** [comment]
I just now saw that there is PR #553 for this.

**Comment by mxmlnkn** [comment]
Python 3.12 did remove `pkg_resources`. Pyfilesystem2 can still be installed, but importing it will fail because of the removed `pkg_resources`.

**Comment by feanil** [comment]
The latest version of [Setuptools (82)](https://setuptools.pypa.io/en/stable/history.html#v82-0-0) drops pkg_resources finally. This means that not having his fix now prevents us from updating setuptools further.

@willmcgugan  @atollk @althonos can one of you help get https://github.com/PyFilesystem/pyfilesystem2/pull/589 and https://github.com/PyFilesystem/pyfilesystem2/pull/590 reviewed, merged and released?

**Comment by atollk** [comment]
@feanil This project hasn't seen an update from the maintainer in years and I haven't spent any time on it since that long either.  tbh I think a better bet for you would be to switch packages to something else

**Comment by dargueta** [comment]
> I think a better bet for you would be to switch packages to something else

[fsspec](https://github.com/fsspec/filesystem_spec/) seems to be the new standard and has greatly improved in the last few years. There are a lot of implementations, such as [s3fs](https://github.com/fsspec/s3fs/) (which Pandas, Polars, PyArrow, and many more use). I recommend using that. You can find a big list of these implementations [here](https://filesystem-spec.readthedocs.io/en/latest/api.html#other-known-implementations).

**Comment by shayneoneill** [comment]
Does anyone have an interim fix? Its not me using this, but an upstream package (eolearn) that is referencing it

**Comment by mxmlnkn** [comment]
Use a dummy `pkg_resources` package. I tested this inside a container:

```bash
python -c 'import fs'
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "/usr/local/lib/python3.12/site-packages/fs/__init__.py", line 4, in <module>
#     __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
#     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
# ModuleNotFoundError: No module named 'pkg_resources'
pip install pkg-resources-backport
python -c 'import fs'   # no error
```

The installed package can also be found here: https://github.com/autumnjolitz/pkg-resources-backport . It seems to be unknown based on the stars and therefore likely unvetted, so a diff to setuptools 81 might be prudent. I found it via the PyPI search.
