### ISSUE TITLE
test_unicode_path fail on FTP [OSX]

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#77]
```
======================================================================
ERROR: test_unicode_path (tests.test_ftpfs.TestFTPFSNoMLSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/will/projects/pyfilesystem2/fs/test.py", line 1730, in test_unicode_path
    self.fs.makedir('földér')
  File "/Users/will/projects/pyfilesystem2/fs/ftpfs.py", line 545, in makedir
    return self.opendir(path)
  File "/Users/will/projects/pyfilesystem2/fs/base.py", line 904, in opendir
    if not self.getbasic(path).is_dir:
  File "/Users/will/projects/pyfilesystem2/fs/base.py", line 1189, in getbasic
    return self.getinfo(path, namespaces=['basic'])
  File "/Users/will/projects/pyfilesystem2/fs/ftpfs.py", line 501, in getinfo
    raise errors.ResourceNotFound(path)
ResourceNotFound: resource 'földér' not found
```

Looks like `FTPFS.makedir` fails to make a directory with that unicode path.

**Comment by willmcgugan** [comment]
Should be fixed in master. The read_dir method was returning `'földér'` but in a different unicode form, which was identical when printed, but compared unequal. Likely due to the accents which can be represented by one or two characters. Fixed in https://github.com/PyFilesystem/pyfilesystem2/commit/5562d59f4dbc5d9441d0ae23ed08d6e929dc5fab

@althonos FYI Probably an OSX specific issue, if you didn't see it.
